### ISSUE TITLE
ipycmc jupyter v3 conversion

### ISSUE THREAD

**Issue by marjo-luc** [MAAP-Project/Community#592]
- [X] build ipycmc in jupyter v2 environment

- [ ] consolidate ipycmc code

- [ ] update ipycmc extension to jupyter v3

- [ ] create github repo for new ipycmc jupyter v3 extension

- [ ] create npm package for ipycmc jupyter v3 extension

**Comment by grallewellyn** [comment]
One of my main problems with this was node-gyp errors which resulted from compatibility issues between node-sass, node, and lib0. I resolved this by using node v14, and in ipycmc package.json changing the value of the dependency "maap-common-mapping-client" from "MAAP-Project/maap-ade-common-mapping-client#stable-pub" to "grallewellyn/maap-test-ade" (which is a repo I made with all the same code as maap ade cmc, but its package.json uses node-sass v6.0.0 so that I don't get node-gyp errors). 
I am now running into access denied errors (despite running the command with sudo). I have tried upgrading rimraf, trying this again in a freshly cloned repo, running sudo chown -R graceal:staff . so all the files are in my name, deleting and reinstalling anaconda- none of these have helped. The error message:
```
> ipycmc@0.1.0 build:labextension
> npm run clean:labextension && mkdirp ipycmc/labextension && cd ipycmc/labextension && npm pack ../..


> ipycmc@0.1.0 clean:labextension
> rimraf ipycmc/labextension

glob error [Error: EACCES: permission denied, scandir '/Users/graceal/Documents/maap/ipycmc-jupyter-extension/dist/tmpp2p9bm1t'] {
  errno: -13,
  code: 'EACCES',
  syscall: 'scandir',
  path: '/Users/graceal/Documents/maap/ipycmc-jupyter-extension/dist/tmpp2p9bm1t'
}
npm ERR! code EACCES
npm ERR! syscall scandir
npm ERR! path /Users/graceal/Documents/maap/ipycmc-jupyter-extension/dist/tmpp2p9bm1t
npm ERR! errno -13
npm ERR! Error: EACCES: permission denied, scandir '/Users/graceal/Documents/maap/ipycmc-jupyter-extension/dist/tmpp2p9bm1t'
npm ERR!  [Error: EACCES: permission denied, scandir '/Users/graceal/Documents/maap/ipycmc-jupyter-extension/dist/tmpp2p9bm1t'] {
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'scandir',
npm ERR!   path: '/Users/graceal/Documents/maap/ipycmc-jupyter-extension/dist/tmpp2p9bm1t'
npm ERR! }
npm ERR! 
npm ERR! The operation was rejected by your operating system.
npm ERR! It is likely you do not have the permissions to access this file as the current user
npm ERR! 
npm ERR! If you believe this might be a permissions issue, please double-check the
npm ERR! permissions of the file and its containing directories, or try running
npm ERR! the command again as root/Administrator.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/graceal/.npm/_logs/2022-11-02T18_55_04_443Z-debug-0.log
error Command failed with exit code 243.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
Traceback (most recent call last):
  File "/Users/graceal/anaconda3/envs/ipycmc2/lib/python3.7/site-packages/pep517/in_process/_in_process.py", line 351, in <module>
    main()
  File "/Users/graceal/anaconda3/envs/ipycmc2/lib/python3.7/site-packages/pep517/in_process/_in_process.py", line 333, in main
    json_out['return_val'] = hook(**hook_input['kwargs'])
  File "/Users/graceal/anaconda3/envs/ipycmc2/lib/python3.7/site-packages/pep517/in_process/_in_process.py", line 302, in build_sdist
    return backend.build_sdist(sdist_directory, config_settings)
  File "/private/tmp/build-env-4a1h79rf/lib/python3.7/site-packages/setuptools/build_meta.py", line 418, in build_sdist
    config_settings)
  File "/private/tmp/build-env-4a1h79rf/lib/python3.7/site-packages/setuptools/build_meta.py", line 397, in _build_with_temp_dir
    self.run_setup()
  File "/private/tmp/build-env-4a1h79rf/lib/python3.7/site-packages/setuptools/build_meta.py", line 484, in run_setup
    self).run_setup(setup_script=setup_script)
  File "/private/tmp/build-env-4a1h79rf/lib/python3.7/site-packages/setuptools/build_meta.py", line 335, in run_setup
    exec(code, locals())
  File "<string>", line 118, in <module>
  File "/private/tmp/build-env-4a1h79rf/lib/python3.7/site-packages/setuptools/__init__.py", line 87, in setup
    return distutils.core.setup(**attrs)
  File "/private/tmp/build-env-4a1h79rf/lib/python3.7/site-packages/setuptools/_distutils/core.py", line 185, in setup
    return run_commands(dist)
  File "/private/tmp/build-env-4a1h79rf/lib/python3.7/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
    dist.run_commands()
  File "/private/tmp/build-env-4a1h79rf/lib/python3.7/site-packages/setuptools/_distutils/dist.py", line 968, in run_commands
    self.run_command(cmd)
  File "/private/tmp/build-env-4a1h79rf/lib/python3.7/site-packages/setuptools/dist.py", line 1217, in run_command
    super().run_command(command)
  File "/private/tmp/build-env-4a1h79rf/lib/python3.7/site-packages/setuptools/_distutils/dist.py", line 987, in run_command
    cmd_obj.run()
  File "/Users/graceal/Documents/maap/ipycmc-jupyter-extension/setupbase.py", line 474, in run
    [self.run_command(cmd) for cmd in cmds]
  File "/Users/graceal/Documents/maap/ipycmc-jupyter-extension/setupbase.py", line 474, in <listcomp>
    [self.run_command(cmd) for cmd in cmds]
  File "/private/tmp/build-env-4a1h79rf/lib/python3.7/site-packages/setuptools/_distutils/cmd.py", line 319, in run_command
    self.distribution.run_command(command)
  File "/private/tmp/build-env-4a1h79rf/lib/python3.7/site-packages/setuptools/dist.py", line 1217, in run_command
    super().run_command(command)
  File "/private/tmp/build-env-4a1h79rf/lib/python3.7/site-packages/setuptools/_distutils/dist.py", line 987, in run_command
    cmd_obj.run()
  File "/Users/graceal/Documents/maap/ipycmc-jupyter-extension/setupbase.py", line 270, in run
    c.run()
  File "/Users/graceal/Documents/maap/ipycmc-jupyter-extension/setupbase.py", line 375, in run
    run(npm_cmd + ['run', build_cmd], cwd=node_package)
  File "/Users/graceal/Documents/maap/ipycmc-jupyter-extension/setupbase.py", line 221, in run
    return subprocess.check_call(cmd, **kwargs)
  File "/Users/graceal/anaconda3/envs/ipycmc2/lib/python3.7/subprocess.py", line 363, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/Users/graceal/.nvm/versions/node/v14.20.1/bin/yarn', 'run', 'build']' returned non-zero exit status 243.

ERROR Backend subprocess exited when trying to invoke build_sdist
```

**Comment by gchang** [comment]
Problem is most likely that this extension is not compatible with our version of jupyterlab. Will look at rewriting the extension.

**Comment by grallewellyn** [comment]
Also, note that Marjorie was successfully able to create a python package from ipycmc

@marjo-luc Can you please send me the code you used to create the python package? And I can start working on changing the jupyterlab version of ipycmc to 3.4.4

**Comment by grallewellyn** [comment]
When I am ready to start working on this, George is going to create a VM for me to test the commands in

**Comment by marjo-luc** [comment]
Closing this ticket as we currently have no plans to support ipycmc in jupyter v3.
